### PR TITLE
Added endpoints for CSP IRA

### PR DESCRIPTION
**Pull request by ywkim312**
There are four new endpoints for CSP IRA created in this PR. The endpoints and the json formats should be identical to eqip-ira.

Please test it with
http://localhost:5000/pdl/titles/title-ii/programs/csp-ira/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/csp-ira/summary
http://localhost:5000/pdl/titles/title-ii/programs/csp-ira/practice-names
http://localhost:5000/pdl/titles/title-ii/programs/csp-ira/predicted

### CODE REVIEW

**Review by pengyin-shan — COMMENTED** [review]
One thing I noticed: for the predicted endpoint, we currently use the predicted prefix for attribute names, such as predictedTotalPaymentInDollars and predictedTotalPaymentPercentageNationwide (see https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/eqip-ira/predicted).

The csp_ira_aggregated_prediction file shows different attribute names. Will these be adjusted later to align with the `eqip-ira` naming convention?

**Comment by ywkim312** [comment]
> One thing I noticed: for the predicted endpoint, we currently use the predicted prefix for attribute names, such as predictedTotalPaymentInDollars and predictedTotalPaymentPercentageNationwide (see https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/eqip-ira/predicted).
> 
> The csp_ira_aggregated_prediction file shows different attribute names. Will these be adjusted later to align with the `eqip-ira` naming convention?

Changed

**Review by pengyin-shan — APPROVED** [review]
Prediction data looks good now. Approving this PR

**Review by sandeep-ps — APPROVED** [review]
In general, the API changes look good to me. There may be some changes to practice category names. For example, 000 might need to be given a short name. I think there was some discussion on it a few weeks ago, but I couldn't find the details in the notes. After we get feedback, we can change this in the data-import and this repo. Thanks.

**Pull request merged**
