### PR TITLE
13 create GitHub action for auto building of container

### PR DESCRIPTION
**Pull request by ywkim312**

### CODE REVIEW

**Comment by ziyue5** [comment]
Hi @ywkim312 , sorry that I am not very familiar with docker-related. Should I test it before I approve this PR? If I should, can I know how I can test it?

**Comment by ywkim312** [comment]
> Hi @ywkim312 , sorry that I am not very familiar with docker-related. Should I test it before I approve this PR? If I should, can I know how I can test it?

If you’re not familiar, it is okay. Let’s wait what @navarroc thinks. If he approves, then let’s merge it

**Comment by navarroc** [comment]
Can you rename gunicorn.config.py to something like gunicorn_conf.py or gunicorn_config.py so there aren't two periods in the name?

**Comment by ywkim312** [comment]
> Can you rename gunicorn.config.py to something like gunicorn_conf.py or gunicorn_config.py so there aren't two periods in the name?

renamed to gunicorn_config.py

**Comment by ywkim312** [comment]
@navarroc the current github action fails because hub.ncsa.illinois.edu is having a problem.

**Comment by navarroc** [comment]
Since you updated the pyproject.toml, I think you need to check in your updated poetry.lock file too.

**Comment by ywkim312** [comment]
> Since you updated the pyproject.toml, I think you need to check in your updated poetry.lock file too.

oh right, added it. sorry

**Comment by navarroc** [comment]
Can you add some basic build/run instructions to the README? We'll want to add the docker build/run instructions and how to run this without docker.

**Comment by navarroc** [comment]
When I try to build the dockerfile I'm seeing an issue about the poetry.lock file being out of date still:

#10 6.869 Installing collected packages: webencodings, trove-classifiers, ptyprocess, msgpack, lockfile, distlib, zipp, urllib3, tomlkit, tomli, six, shellingham, rapidfuzz, pyrsistent, pycparser, poetry-core, platformdirs, pkginfo, pexpect, packaging, more-itertools, jeepney, idna, filelock, crashtest, charset-normalizer, certifi, attrs, virtualenv, requests, jsonschema, jaraco.classes, importlib-metadata, html5lib, dulwich, cleo, cffi, requests-toolbelt, cryptography, cachecontrol, SecretStorage, keyring, poetry-plugin-export, poetry
#10 10.05 Successfully installed SecretStorage-3.3.3 attrs-22.1.0 cachecontrol-0.12.11 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-2.1.1 cleo-2.0.1 crashtest-0.4.1 cryptography-38.0.4 distlib-0.3.6 dulwich-0.20.50 filelock-3.8.2 html5lib-1.1 idna-3.4 importlib-metadata-4.13.0 jaraco.classes-3.2.3 jeepney-0.8.0 jsonschema-4.17.3 keyring-23.13.1 lockfile-0.12.2 more-itertools-9.0.0 msgpack-1.0.4 packaging-22.0 pexpect-4.8.0 pkginfo-1.9.2 platformdirs-2.6.0 poetry-1.3.1 poetry-core-1.4.0 poetry-plugin-export-1.2.0 ptyprocess-0.7.0 pycparser-2.21 pyrsistent-0.19.2 rapidfuzz-2.13.6 requests-2.28.1 requests-toolbelt-0.10.1 shellingham-1.5.0 six-1.16.0 tomli-2.0.1 tomlkit-0.11.6 trove-classifiers-2022.12.1 urllib3-1.26.13 virtualenv-20.17.1 webencodings-0.5.1 zipp-3.11.0
#10 10.05 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#10 DONE 10.4s

#11 [7/8] RUN poetry install
#11 sha256:d105a4b1eb533688e2d229328df3bdfe97cdb801a8e2666699ba840ba209ad81
#11 0.756 Skipping virtualenv creation, as specified in config file.
#11 0.928 Installing dependencies from lock file
#11 1.117 Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
#11 1.165 
#11 1.165 Because pdl-api depends on gevent (>=20.9.0) which doesn't match any versions, version solving failed.
#11 ERROR: executor failed running [/bin/sh -c poetry install]: exit code: 1

**Comment by navarroc** [comment]
I think you need to do a poetry update on your local so it updates the poetry.lock file with the gevent version you specified. I noticed the poetry.lock file doesn't have the version you set in there. 

> When I try to build the dockerfile I'm seeing an issue about the poetry.lock file being out of date still:
> 
> #10 6.869 Installing collected packages: webencodings, trove-classifiers, ptyprocess, msgpack, lockfile, distlib, zipp, urllib3, tomlkit, tomli, six, shellingham, rapidfuzz, pyrsistent, pycparser, poetry-core, platformdirs, pkginfo, pexpect, packaging, more-itertools, jeepney, idna, filelock, crashtest, charset-normalizer, certifi, attrs, virtualenv, requests, jsonschema, jaraco.classes, importlib-metadata, html5lib, dulwich, cleo, cffi, requests-toolbelt, cryptography, cachecontrol, SecretStorage, keyring, poetry-plugin-export, poetry #10 10.05 Successfully installed SecretStorage-3.3.3 attrs-22.1.0 cachecontrol-0.12.11 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-2.1.1 cleo-2.0.1 crashtest-0.4.1 cryptography-38.0.4 distlib-0.3.6 dulwich-0.20.50 filelock-3.8.2 html5lib-1.1 idna-3.4 importlib-metadata-4.13.0 jaraco.classes-3.2.3 jeepney-0.8.0 jsonschema-4.17.3 keyring-23.13.1 lockfile-0.12.2 more-itertools-9.0.0 msgpack-1.0.4 packaging-22.0 pexpect-4.8.0 pkginfo-1.9.2 platformdirs-2.6.0 poetry-1.3.1 poetry-core-1.4.0 poetry-plugin-export-1.2.0 ptyprocess-0.7.0 pycparser-2.21 pyrsistent-0.19.2 rapidfuzz-2.13.6 requests-2.28.1 requests-toolbelt-0.10.1 shellingham-1.5.0 six-1.16.0 tomli-2.0.1 tomlkit-0.11.6 trove-classifiers-2022.12.1 urllib3-1.26.13 virtualenv-20.17.1 webencodings-0.5.1 zipp-3.11.0 #10 10.05 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv #10 DONE 10.4s
> 
> #11 [7/8] RUN poetry install #11 sha256:d105a4b1eb533688e2d229328df3bdfe97cdb801a8e2666699ba840ba209ad81 #11 0.756 Skipping virtualenv creation, as specified in config file. #11 0.928 Installing dependencies from lock file #11 1.117 Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it. #11 1.165 #11 1.165 Because pdl-api depends on gevent (>=20.9.0) which doesn't match any versions, version solving failed. #11 ERROR: executor failed running [/bin/sh -c poetry install]: exit code: 1

**Comment by ywkim312** [comment]
> I think you need to do a poetry update on your local so it updates the poetry.lock file with the gevent version you specified. I noticed the poetry.lock file doesn't have the version you set in there.
> 
> > When I try to build the dockerfile I'm seeing an issue about the poetry.lock file being out of date still:
> > #10 6.869 Installing collected packages: webencodings, trove-classifiers, ptyprocess, msgpack, lockfile, distlib, zipp, urllib3, tomlkit, tomli, six, shellingham, rapidfuzz, pyrsistent, pycparser, poetry-core, platformdirs, pkginfo, pexpect, packaging, more-itertools, jeepney, idna, filelock, crashtest, charset-normalizer, certifi, attrs, virtualenv, requests, jsonschema, jaraco.classes, importlib-metadata, html5lib, dulwich, cleo, cffi, requests-toolbelt, cryptography, cachecontrol, SecretStorage, keyring, poetry-plugin-export, poetry #10 10.05 Successfully installed SecretStorage-3.3.3 attrs-22.1.0 cachecontrol-0.12.11 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-2.1.1 cleo-2.0.1 crashtest-0.4.1 cryptography-38.0.4 distlib-0.3.6 dulwich-0.20.50 filelock-3.8.2 html5lib-1.1 idna-3.4 importlib-metadata-4.13.0 jaraco.classes-3.2.3 jeepney-0.8.0 jsonschema-4.17.3 keyring-23.13.1 lockfile-0.12.2 more-itertools-9.0.0 msgpack-1.0.4 packaging-22.0 pexpect-4.8.0 pkginfo-1.9.2 platformdirs-2.6.0 poetry-1.3.1 poetry-core-1.4.0 poetry-plugin-export-1.2.0 ptyprocess-0.7.0 pycparser-2.21 pyrsistent-0.19.2 rapidfuzz-2.13.6 requests-2.28.1 requests-toolbelt-0.10.1 shellingham-1.5.0 six-1.16.0 tomli-2.0.1 tomlkit-0.11.6 trove-classifiers-2022.12.1 urllib3-1.26.13 virtualenv-20.17.1 webencodings-0.5.1 zipp-3.11.0 #10 10.05 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv #10 DONE 10.4s
> > #11 [7/8] RUN poetry install #11 sha256:d105a4b1eb533688e2d229328df3bdfe97cdb801a8e2666699ba840ba209ad81 #11 0.756 Skipping virtualenv creation, as specified in config file. #11 0.928 Installing dependencies from lock file #11 1.117 Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it. #11 1.165 #11 1.165 Because pdl-api depends on gevent (>=20.9.0) which doesn't match any versions, version solving failed. #11 ERROR: executor failed running [/bin/sh -c poetry install]: exit code: 1

hmmm can this be window problem? I made it using the VM and updated it. The docker build and run was succesful

**Review by navarroc — APPROVED** [review]

**Pull request merged**
