### PR TITLE
182 feature update title 1 endpoints to extract data from the database

### PR DESCRIPTION
**Pull request by sandeep-ps**
This PR updates the Title 1 endpoints to use database queries instead of JSON files. The data has already been inserted into the PDL API development database. If you want to create your own database locally, please follow the instructions in the new https://github.com/policy-design-lab/data-ingestion/ repository. 

You can test the changes in this PR by connecting the API with the frontend running locally and comparing it with the DEV frontend. Thanks.

You can observe a few minor differences between values in the local instance and the deployed instance, which are due to the difference in the way numbers are rounded off.

Please let me know if you have any questions. Thanks.

### CODE REVIEW

**Comment by ywkim312** [comment]
@sandeep-ps Can you provide the way to connect to the actual database so I can connect from local api to database? Like db url, db name, and password and so on? Maybe you can DM to me using slack, or if there is other way please let me know

**Comment by sandeep-ps** [comment]
Hi, Yongwook, this is using the existing connection method used by pdl-api. So, having a .env file with appropriate credentials, and being on VPN, should be sufficient. Please let me know if you see any issues with connecting.

**Comment by ywkim312** [comment]
> Hi, Yongwook, this is using the existing connection method used by pdl-api. So, having a .env file with appropriate credentials, and being on VPN, should be sufficient. Please let me know if you see any issues with connecting.
> 
> https://github.com/policy-design-lab/pdl-api/pull/183/files#diff-0e610bd80b82d9a5775cc5c535e5545d714f53bdb817923a2cd32debe71588ba

I think that I don't have .env file

**Comment by ywkim312** [comment]
This is a difference from /pdl/titles/title-i/subtitles/subtitle-a/state-distribution
left is dev site and right is your PR

image

**Comment by ywkim312** [comment]
/pdl/titles/title-i/subtitles/subtitle-a/map looks identical

**Comment by ywkim312** [comment]
subtitle-d's summary values are different

dev site
{
  "subtitleName": "Dairy Margin Coverage, Subtitle D",
  "totalPaymentInDollars": 1969315257.26,
  "totalCounts": 1259532,
  "averageRecipientCount": 157441.5,
  "programs": []
}

PR
{
  "subtitleName": "Dairy Margin Coverage, Subtitle D",
  "totalPaymentInDollars": 1969315257.26,
  "totalCounts": 542644,
  "averageRecipientCount": 67831,
  "programs": []
}

**Comment by ywkim312** [comment]
state distribution for subtitle D has the similar difference pattern as subtitle A

also subtitle E also having similar issue

**Comment by sandeep-ps** [comment]
> I see the difference in output from pdl/titles/title-i/subtitles/subtitle-a/summary image
> 
> Left is dev site and right side is local host using your PR Keep check the other title I endpoints

I think it's the other way around. The left side should be local. I have added more datapoints, but the current data is preserved. It can be removed if needed.

**Comment by sandeep-ps** [comment]
> This is a difference from /pdl/titles/title-i/subtitles/subtitle-a/state-distribution left is dev site and right is your PR
> 
> image

I think here also, it's a similar situation. Previously, only some endpoints in Title 1 used to return some attributes like totalCounts. I just tried to make it uniform so that all endpoints in Title 1 return same attributes (using a single function for all endpoints in Title 1). Also, I think it was discussed in a meeting recently that it would be good to show the percentages at all levels.

**Comment by sandeep-ps** [comment]
> subtitle-d's summary values are different
> 
> dev site { "subtitleName": "Dairy Margin Coverage, Subtitle D", "totalPaymentInDollars": 1969315257.26, "totalCounts": 1259532, "averageRecipientCount": 157441.5, "programs": [] }
> 
> PR { "subtitleName": "Dairy Margin Coverage, Subtitle D", "totalPaymentInDollars": 1969315257.26, "totalCounts": 542644, "averageRecipientCount": 67831, "programs": [] }

HI, Yongwook, I revisited the Dairy-Disaster.csv in data-import respository, and use pivot tables to calculate the total and average recipient count. Please see the screenshot below. The Grand Total and the value to the right of it (average count) matches the one in this PR. I hope this helps to resolve this difference you observed.

image

**Comment by sandeep-ps** [comment]
> state distribution for subtitle D has the similar difference pattern as subtitle A
> 
> also subtitle E also having similar issue as Subtitle D

I suppose these are also newer attributes being present in the PR. Please let me know if otherwise. 

Please see that Subtitle E summary (local) is the same as Subtitle E (develop) except for newer attributes for percentage and subPrograms:

**Subtitle E Summary (PR)**

```
{
    "subtitleName": "Supplemental Agricultural Disaster Assistance, Subtitle E",
    "totalPaymentInDollars": 4589389922.13,
    "totalCounts": 716888,
    "averageRecipientCount": 89611,
    "programs": [
        {
            "programName": "Emergency Assistance for Livestock, Honey Bees, and Farm-Raised Fish Program (ELAP)",
            "totalPaymentInDollars": 336365634.1,
            "totalCounts": 27330,
            "averageRecipientCount": 3416,
            "totalPaymentInPercentage": 7.33,
            "subPrograms": []
        },
        {
            "programName": "Livestock Forage Program (LFP)",
            "totalPaymentInDollars": 3881887342.49,
            "totalCounts": 640521,
            "averageRecipientCount": 80065,
            "totalPaymentInPercentage": 84.58,
            "subPrograms": []
        },
        {
            "programName": "Livestock Indemnity Payments (LIP)",
            "totalPaymentInDollars": 284805659.06,
            "totalCounts": 45063,
            "averageRecipientCount": 5633,
            "totalPaymentInPercentage": 6.21,
            "subPrograms": []
        },
        {
            "programName": "Tree Assistance Program (TAP)",
            "totalPaymentInDollars": 86331286.48,
            "totalCounts": 3974,
            "averageRecipientCount": 497,
            "totalPaymentInPercentage": 1.88,
            "subPrograms": []
        }
    ]
}
```

**Subtitle E Summary (Dev)**

```
{
    "subtitleName": "Supplemental Agricultural Disaster Assistance, Subtitle E",
    "totalPaymentInDollars": 4589389922.13,
    "totalCounts": 716888,
    "averageRecipientCount": 89611.0,
    "programs": [
        {
            "programName": "Emergency Assistance for Livestock, Honey Bees, and Farm-Raised Fish Program (ELAP)",
            "totalPaymentInDollars": 336365634.1,
            "totalCounts": 27330,
            "averageRecipientCount": 3416.25
        },
        {
            "programName": "Livestock Forage Program (LFP)",
            "totalPaymentInDollars": 3881887342.49,
            "totalCounts": 640521,
            "averageRecipientCount": 80065.12
        },
        {
            "programName": "Livestock Indemnity Payments (LIP)",
            "totalPaymentInDollars": 284805659.06,
            "totalCounts": 45063,
            "averageRecipientCount": 5632.88
        },
        {
            "programName": "Tree Assistance Program (TAP)",
            "totalPaymentInDollars": 86331286.48,
            "totalCounts": 3974,
            "averageRecipientCount": 496.75
        }
    ]
}
```

**Comment by ywkim312** [comment]
> > state distribution for subtitle D has the similar difference pattern as subtitle A
> > also subtitle E also having similar issue as Subtitle D
> 
> I suppose these are also newer attributes being present in the PR. Please let me know if otherwise.
> 
> Please see that Subtitle E summary (local) is the same as Subtitle E (develop) except for newer attributes for percentage and subPrograms:
> 
> **Subtitle E Summary (PR)**
> 
> ```
> {
>     "subtitleName": "Supplemental Agricultural Disaster Assistance, Subtitle E",
>     "totalPaymentInDollars": 4589389922.13,
>     "totalCounts": 716888,
>     "averageRecipientCount": 89611,
>     "programs": [
>         {
>             "programName": "Emergency Assistance for Livestock, Honey Bees, and Farm-Raised Fish Program (ELAP)",
>             "totalPaymentInDollars": 336365634.1,
>             "totalCounts": 27330,
>             "averageRecipientCount": 3416,
>             "totalPaymentInPercentage": 7.33,
>             "subPrograms": []
>         },
>         {
>             "programName": "Livestock Forage Program (LFP)",
>             "totalPaymentInDollars": 3881887342.49,
>             "totalCounts": 640521,
>             "averageRecipientCount": 80065,
>             "totalPaymentInPercentage": 84.58,
>             "subPrograms": []
>         },
>         {
>             "programName": "Livestock Indemnity Payments (LIP)",
>             "totalPaymentInDollars": 284805659.06,
>             "totalCounts": 45063,
>             "averageRecipientCount": 5633,
>             "totalPaymentInPercentage": 6.21,
>             "subPrograms": []
>         },
>         {
>             "programName": "Tree Assistance Program (TAP)",
>             "totalPaymentInDollars": 86331286.48,
>             "totalCounts": 3974,
>             "averageRecipientCount": 497,
>             "totalPaymentInPercentage": 1.88,
>             "subPrograms": []
>         }
>     ]
> }
> ```
> 
> **Subtitle E Summary (Dev)**
> 
> ```
> {
>     "subtitleName": "Supplemental Agricultural Disaster Assistance, Subtitle E",
>     "totalPaymentInDollars": 4589389922.13,
>     "totalCounts": 716888,
>     "averageRecipientCount": 89611.0,
>     "programs": [
>         {
>             "programName": "Emergency Assistance for Livestock, Honey Bees, and Farm-Raised Fish Program (ELAP)",
>             "totalPaymentInDollars": 336365634.1,
>             "totalCounts": 27330,
>             "averageRecipientCount": 3416.25
>         },
>         {
>             "programName": "Livestock Forage Program (LFP)",
>             "totalPaymentInDollars": 3881887342.49,
>             "totalCounts": 640521,
>             "averageRecipientCount": 80065.12
>         },
>         {
>             "programName": "Livestock Indemnity Payments (LIP)",
>             "totalPaymentInDollars": 284805659.06,
>             "totalCounts": 45063,
>             "averageRecipientCount": 5632.88
>         },
>         {
>             "programName": "Tree Assistance Program (TAP)",
>             "totalPaymentInDollars": 86331286.48,
>             "totalCounts": 3974,
>             "averageRecipientCount": 496.75
>         }
>     ]
> }
> ```

Yes, the values matched but there was differences in attributes. But it resolved by yesterday's conversation, so I think that it should be okay. Let me check one more time overall

**Review by ywkim312 — APPROVED** [review]

**Comment by sandeep-ps** [comment]
Thanks Yongwook, for reviewing.

Hi, Chris and Pengyin, I have updated the DEV instance to point to the Docker image of this PR. Please let me know if you have any feedback. Thanks.

**Comment by sandeep-ps** [comment]
Hi, @navarroc or @pengyin-shan, do you have feedback on this PR? If not, I would like to merge this PR, as there are follow up PRs that need to be reviewed. Thanks.

**Comment by pengyin-shan** [comment]
Hi @sandeep-ps , sorry I thought this PR was still in process since discussions were going on. 

I compared the dev version and production title I page, and I noticed the Total Recipients Count Pct. Within State for ELAP, LFP, LIP and TAP:
Screenshot 2024-04-26 at 10 18 34 AM

Screenshot 2024-04-26 at 10 22 53 AM


Based on your conversations above, I know we have some changes in Subtitle E calculations, may I assume these differences are what we expected? Other attributes in Subtitle E are matching well and Subtitle E summary is also correct.

**Comment by sandeep-ps** [comment]
Hi, @pengyin-shan, I'm looking into this one more time just to be sure. Thanks.

**Comment by sandeep-ps** [comment]
I think I understood what's happening. It looks like we have two attributes `totalCountsInPercentageWithinState` and `averageRecipientCountInPercentageWithinState`. They both contain the same value in the production instance. I interpreted that we need to store the percentage of **average** recipients within a state in both these fields. The previous code was storing the percentage of **total** recipients within a state both these fields. I will fix this, but I think at some point the frontend code needs to switch to using `totalCountsInPercentageWithinState`, and in the backend we should have different values stored in these variables (one being the percentage of total and the other being the percentage of average) or remove the one that's no longer needed. Thanks for finding this.

**Comment by sandeep-ps** [comment]
Hi, Pengyin, The fix has been deployed to the Dev instance. Please see when you get a chance. Thanks.

**Review by pengyin-shan — APPROVED** [review]
The updated version has the matched `TOTAL RECIPIENTS COUNT PCT. WITHIN STATE` data. We can update this attribute in the future. Approvinig this PR.

**Comment by sandeep-ps** [comment]
Thanks for all the feedback. Merging this PR.

**Pull request merged**
