### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by ywkim312**

### CODE REVIEW

**Review by sandeep-ps — APPROVED** [review]
I compared the responses of the new endpoints with the old endpoints, and the changes look good to me. I will approve.

**Comment by ywkim312** [comment]
> Worked well on the front-end. @ywkim312 as a note, in the future we can retire the map endpoint for EQIP and CSP. I revised their code to use the state-distributon and summary endpoint only instead.

Yes I am planning to retire the old endpoints when you let me know that the front end is not using the old one any more. Is it already like that?

**Comment by pengyin-shan** [comment]
> > Worked well on the front-end. @ywkim312 as a note, in the future we can retire the map endpoint for EQIP and CSP. I revised their code to use the state-distributon and summary endpoint only instead.
> 
> Yes I am planning to retire the old endpoints when you let me know that the front end is not using the old one any more. Is it already like that?

Please retire the old endpoint for Titel I, Title II, and Crop Insurance **after** this upcoming front-end release because I want it to run for a while to ensure everything is still good. I think SNAP and Landing page don't have new endpoints right?

**Comment by ywkim312** [comment]
> > > Worked well on the front-end. @ywkim312 as a note, in the future we can retire the map endpoint for EQIP and CSP. I revised their code to use the state-distributon and summary endpoint only instead.
> > 
> > 
> > Yes I am planning to retire the old endpoints when you let me know that the front end is not using the old one any more. Is it already like that?
> 
> Please retire the old endpoint for Titel I, Title II, and Crop Insurance **after** this upcoming front-end release because I want it to run for a while to ensure everything is still good. I think SNAP and Landing page don't have new endpoints right?

yes there are endpoints for SNAP like
https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-iv/programs/snap/state-distribution

which enpoint you use for landing page?

**Comment by pengyin-shan** [comment]
> > > > Worked well on the front-end. @ywkim312 as a note, in the future we can retire the map endpoint for EQIP and CSP. I revised their code to use the state-distributon and summary endpoint only instead.
> > > 
> > > 
> > > Yes I am planning to retire the old endpoints when you let me know that the front end is not using the old one any more. Is it already like that?
> > 
> > 
> > Please retire the old endpoint for Titel I, Title II, and Crop Insurance **after** this upcoming front-end release because I want it to run for a while to ensure everything is still good. I think SNAP and Landing page don't have new endpoints right?
> 
> yes there are endpoints for SNAP like https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-iv/programs/snap/state-distribution
> 
> which enpoint you use for landing page?

Oh I saw there are discussions about SNAP should keep as it is. Should I also switch the endpoint of SNAP?

For landing page, they are https://policydesignlab-dev.ncsa.illinois.edu/pdl/summary and https://policydesignlab-dev.ncsa.illinois.edu/pdl/allprograms

**Comment by ywkim312** [comment]
> https://policydesignlab-dev.ncsa.illinois.edu/pdl/summary and https://policydesignlab-dev.ncsa.illinois.edu/pdl/allprograms

Sorry for the late reply. You have already change to new endpoint right?

**Comment by pengyin-shan** [comment]
> > https://policydesignlab-dev.ncsa.illinois.edu/pdl/summary and https://policydesignlab-dev.ncsa.illinois.edu/pdl/allprograms
> 
> Sorry for the late reply. You have already change to new endpoint right?

SNAP yes, but not https://policydesignlab-dev.ncsa.illinois.edu/pdl/allprograms. Do we have a new endpoint for this?

**Comment by ywkim312** [comment]
> > > https://policydesignlab-dev.ncsa.illinois.edu/pdl/summary and https://policydesignlab-dev.ncsa.illinois.edu/pdl/allprograms
> > 
> > 
> > Sorry for the late reply. You have already change to new endpoint right?
> 
> SNAP yes, but not https://policydesignlab-dev.ncsa.illinois.edu/pdl/allprograms. Do we have a new endpoint for this?

No we don't, I will see if we can refactor or if it is not needed. Thank you for your help. I will merge this PR and release

**Pull request merged**
