### PR TITLE
replaced hawaii/pacific to hawaii

### PR DESCRIPTION
**Pull request by ywkim312**

### CODE REVIEW

**Comment by pengyin-shan** [comment]
@ywkim312 we also need to do this to acpp data

**Comment by ywkim312** [comment]
> @ywkim312 we also need to do this to acpp data

I see. I will fix acep data-import and add it to in this PR and will let you know

**Comment by ywkim312** [comment]
> @ywkim312 we also need to do this to acpp data

acep data modified

**Comment by pengyin-shan** [comment]
sorry @ywkim312 did you change the attribute name of API? May I ask why?

**Comment by ywkim312** [comment]
> sorry @ywkim312 did you change the attribute name of API? May I ask why?

totalPayment to just Payment? I changed it because I found out the other ones using that.

**Review by navarroc — APPROVED** [review]

**Comment by pengyin-shan** [comment]
> > sorry @ywkim312 did you change the attribute name of API? May I ask why?
> 
> totalPayment to just Payment? I changed it because I found out the other ones using that.

Ah I see, actually totalPaymentInDollars might be better because we can skip the front-end transformation in the future (this is a kind of tech debt...we had the transfer from payment to totalPayment, then other codes have to inherit it).

**Comment by ywkim312** [comment]
> > > sorry @ywkim312 did you change the attribute name of API? May I ask why?
> > 
> > 
> > totalPayment to just Payment? I changed it because I found out the other ones using that.
> 
> Ah I see, actually totalPaymentInDollars might be better because we can skip the front-end transformation in the future (this is a kind of tech debt...we had the transfer from payment to totalPayment, then other codes have to inherit it).

I will revert it

**Comment by pengyin-shan** [comment]
> > > > sorry @ywkim312 did you change the attribute name of API? May I ask why?
> > > 
> > > 
> > > totalPayment to just Payment? I changed it because I found out the other ones using that.
> > 
> > 
> > Ah I see, actually totalPaymentInDollars might be better because we can skip the front-end transformation in the future (this is a kind of tech debt...we had the transfer from payment to totalPayment, then other codes have to inherit it).
> 
> I will revert it

thank you!!

**Comment by ywkim312** [comment]
> > > > > sorry @ywkim312 did you change the attribute name of API? May I ask why?
> > > > 
> > > > 
> > > > totalPayment to just Payment? I changed it because I found out the other ones using that.
> > > 
> > > 
> > > Ah I see, actually totalPaymentInDollars might be better because we can skip the front-end transformation in the future (this is a kind of tech debt...we had the transfer from payment to totalPayment, then other codes have to inherit it).
> > 
> > 
> > I will revert it
> 
> thank you!!

reverted. So only Hawaii is the change

**Pull request merged**
