### PR TITLE
Added EQIP IRA endpoints

### PR DESCRIPTION
**Pull request by ywkim312**
Two new endpoints added

http://localhost:5000/pdl/titles/title-ii/programs/eqip-ira/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/eqip-ira/summary

This is also deployed to dev instance

### CODE REVIEW

**Review by pengyin-shan — APPROVED** [review]
The proposed URL matched our existing `pdl/titles/title-ii/programs/eqip/state-distribution` format well. Approving this PR.

**Comment by ywkim312** [comment]
> @ywkim312 @sandeep-ps: May I confirm that after today's meeting, the data and data structure in this API is going to change? Or can I use this as the decided version of the data for front-end development?

I am not sure. Since at least you're comfortable with the data structure, I have no objection. @sandeep-ps what do you think? Also, there is a PR for this in data import repo, so please review it as well when you have a chance

**Comment by sandeep-ps** [comment]
Hi, Yongwook and Pengyin, I'm sorry for getting back late to this and the data import PRs. I wouldn't suggest significant changes now. Some potential future improvements would be splitting practice code and name into separate attributes and including categories discussed today. I will review this and the other PR this afternoon and share feedback.

**Comment by pengyin-shan** [comment]
> Hi, Yongwook and Pengyin, I'm sorry for getting back late to this and the data import PRs. I wouldn't suggest significant changes now. Some potential future improvements would be splitting practice code and name into separate attributes and including categories discussed today. I will review this and the other PR this afternoon and share feedback.

Cool, I will continue to use the endpoint provided by this PR to proceed with front-end development, until we expect significant change coming. Thank you @sandeep-ps and @ywkim312 for confirming this!

**Review by sandeep-ps — APPROVED** [review]
I briefly tested this PR using the deployed development instance. The responses look good to me. I will approve.

**Pull request merged**
