### PR TITLE
Added statute-level percentages to CSP JSON data.

### PR DESCRIPTION
**Pull request by sandeep-ps**

### CODE REVIEW

**Comment by sandeep-ps** [comment]
The docker build has succeeded. Please review this PR.

**Review by pengyin-shan — APPROVED** [review]
Thank you, tested and worked well on the CSP page. Just wondering do you also want to update to 'Grassland' in this PR? Or you can do this in another PR to update both json files?

**Comment by sandeep-ps** [comment]
Hi, @pengyin-shan, I have updated this PR. Please see.

**Comment by pengyin-shan** [comment]
> Hi, @pengyin-shan, I have updated this PR. Please see.

Looks great, thank you!

**Review by ywkim312 — APPROVED** [review]

**Pull request merged**
