### PR TITLE
278 bug fix snap average monthly participation calculation

### PR DESCRIPTION
**Pull request by sandeep-ps**

### CODE REVIEW

**Comment by sandeep-ps** [comment]
The development instance is deployed with this change.

**Comment by sandeep-ps** [comment]
Production instance:

image


Development instance with corrected calculation:

image

**Comment by navarroc** [comment]
Should we round to the nearest whole number for avg monthly participation?  Other than that, this looks good.

**Comment by sandeep-ps** [comment]
> Should we round to the nearest whole number for avg monthly participation? Other than that, this looks good.

Yes, we should. Pushed the change.

**Review by navarroc — APPROVED** [review]
Looks good. Ran locally and tested the changes

**Pull request merged**
