### PR TITLE
Fix missing attributes in CSP response statute objects.

### PR DESCRIPTION
**Pull request by sandeep-ps**

### CODE REVIEW

**Comment by ywkim312** [comment]
Code looks good but can it be deployed in dev and to see if it works?

**Review by pengyin-shan — APPROVED** [review]
The two missing statues are added attributes in this PR. Approving.

**Comment by sandeep-ps** [comment]
I have deployed this branch. Thanks.

**Review by ywkim312 — APPROVED** [review]

**Comment by ywkim312** [comment]
> I have deployed this branch. Thanks.

Thank you!

**Pull request merged**
