### PR TITLE
275 feature add query parameter to filter title ii state distribution endpoints based on practice codes

### PR DESCRIPTION
**Pull request by sandeep-ps**
This PR adds payment by practice codes within the practice category dictionary in the state-distribution response, and adds a query parameter to filter based on specific practice codes.

E.g. requests:
EQIP

https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/eqip/state-distribution?practice_code=313,325,340,412
https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/eqip/state-distribution

CSP:
https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/csp/state-distribution?practice_code=315,NIPF
https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/csp/state-distribution

NB: Please note that the query parameter name is `practice_code` instead of `practice_codes` that was discussed in Slack. This change is to support the convention to query by a single practice code and also the idea that the comma separated format is actually an alternative (supported by OpenAPI specification) for the format `practice_code=a&practice_code=b`. That said, this format is not supported in the current backend implementation as it can lead to long URLs that can potentially exceed the maximum supported URL length (2048 characters in many cases).

### CODE REVIEW

**Review by pengyin-shan — APPROVED** [review]
Approve this PR and will work on the front end accordingly.

One thing to confirm: if I run a request and receive no results (e.g., https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/eqip/state-distribution?practice_code=161), does this mean the corresponding practice code doesn't have any data?

**Comment by sandeep-ps** [comment]
> Approve this PR and will work on the front end accordingly.
> 
> One thing to confirm: if I run a request and receive no results (e.g., https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/eqip/state-distribution?practice_code=161), does this mean the corresponding practice code doesn't have any data?

In the above request's response, there is one entry with "Pest Management Conservation System Design (161)" for the state of Indiana. But, yes, in general, if a specific state doesn't have payment data with the provided query parameter, it will return empty list indicating the practice code is not existing for that state and year duration in the database.

**Comment by pengyin-shan** [comment]
> > Approve this PR and will work on the front end accordingly.
> > One thing to confirm: if I run a request and receive no results (e.g., https://policydesignlab-dev.ncsa.illinois.edu/pdl/titles/title-ii/programs/eqip/state-distribution?practice_code=161), does this mean the corresponding practice code doesn't have any data?
> 
> In the above request's response, there is one entry with "Pest Management Conservation System Design (161)" for the state of Indiana. But, yes, in general, if a specific state doesn't have payment data with the provided query parameter, it will return empty list indicating the practice code is not existing for that state and year duration in the database.

Ah cool, thanks!

**Comment by sandeep-ps** [comment]
@navarroc and @ylyangtw, Please let me know if you have additional feedback. If not, I can merge this PR. Thanks.

**Review by ylyangtw — APPROVED** [review]
Changes look good to me

**Review by navarroc — APPROVED** [review]

**Comment by sandeep-ps** [comment]
> Regarding your comment about the URL length. Would we want to at some point consider using a POST so we can put the practice codes in the request body?

Maybe not. After doing another check, it looks like most browsers support maximum URL lengths in the range 2K - 30K characters. The minimum of that range should be sufficient to support more than 475 practice codes in the URL. When there are other clients that can programmatically request more practice codes, yes, we could consider changing to POST.

**Pull request merged**
