### PR TITLE
Create an endpoint for title ii conservation csp

### PR DESCRIPTION
**Pull request by ywkim312**

### CODE REVIEW

**Review by sandeep-ps — COMMENTED** [review]
I tested this using Postman. The endpoints are running fine. Please update the JSON files with the latest one in Box. Thanks.

**Comment by pengyin-shan** [comment]
I'm testing it. Will post here soon

**Review by pengyin-shan — APPROVED** [review]
Tested and works. thank you!

**Comment by pengyin-shan** [comment]
Please make sure the docker error is fixed before you merge your changes.

**Comment by ywkim312** [comment]
> I tested this using Postman. The endpoints are running fine. Please update the JSON files with the latest one in Box. Thanks.

Updated the json files to newest ones

**Review by sandeep-ps — APPROVED** [review]

**Pull request merged**
