### PR TITLE
Update api endpoints with new data and new url for title i and title ii

### PR DESCRIPTION
**Pull request by ywkim312**
Please test the following endpoints. The content of JSON files has not been updated yet. There are PRs in data-import REO.
Title I
Subtitle A and others (ARC, PLC)
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-a/map
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-a/state-distribution
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-a/subprograms

Subtitle D
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-d/state-distribution
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-d/subprograms

Subtitle E
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-e/state-distribution
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-e/subprograms

Title II
EQIP
http://localhost:5000/pdl/titles/title-ii/programs/eqip/map
http://localhost:5000/pdl/titles/title-ii/programs/eqip/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/eqip/practice-categories

CSP
http://localhost:5000/pdl/titles/title-ii/programs/csp/map
http://localhost:5000/pdl/titles/title-ii/programs/csp/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/csp/practice-categories

CRP
http://localhost:5000/pdl/titles/title-ii/programs/crp/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/crp/subprograms

ACEP
http://localhost:5000/pdl/titles/title-ii/programs/acep/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/acep/subprograms

RCPP
http://localhost:5000/pdl/titles/title-ii/programs/rcpp/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/rcpp/subprograms

These are the old and new endpoints

Title I Subtitle A and others (ARC, PLC)
/pdl/programs/commodities/map
-- /pdl/titles/title-i/subtitles/subtitle-a/map:
/pdl/programs/commodities/state-distribution
-- /pdl/titles/title-i/subtitles/subtitle-a/state-distribution:
/pdl/programs/commodities/subprograms
-- /pdl/titles/title-i/subtitles/subtitle-a/subprograms:

Title I Subtitle D
/pdl/programs/commodities/dmc/state-distribution
-- /pdl/titles/title-i/subtitles/subtitle-d/state-distribution:
/pdl/programs/commodities/dmc/subprograms
-- /pdl/titles/title-i/subtitles/subtitle-d/subprograms:

Title I Subtitle E
/pdl/programs/commodities/sada/state-distribution
-- /pdl/titles/title-i/subtitles/subtitle-e/state-distribution:
/pdl/programs/commodities/sada/subprograms
-- /pdl/titles/title-i/subtitles/subtitle-e/subprograms:

Title II EQIP
/pdl/programs/conservation/eqip/map
-- /pdl/titles/title-ii/programs/eqip/map
/pdl/programs/conservation/eqip/state-distribution
-- /pdl/titles/title-ii/programs/eqip/state-distribution
/pdl/programs/conservation/eqip/practice-categories
-- /pdl/titles/title-ii/programs/eqip/practice-categories

Title II CSP
/pdl/programs/conservation/csp/map
-- /pdl/titles/title-ii/programs/csp/map
/pdl/programs/conservation/csp/state-distribution
-- /pdl/titles/title-ii/programs/csp/state-distribution
/pdl/programs/conservation/csp/practice-categories
-- /pdl/titles/title-ii/programs/csp/practice-categories

Title II CRP
/pdl/programs/conservation/crp/state-distribution
-- /pdl/titles/title-ii/programs/crp/state-distribution
/pdl/programs/conservation/crp/subprograms
-- /pdl/titles/title-ii/programs/crp/subprograms

Title II ACEP
/pdl/programs/conservation/acep/state-distribution
-- /pdl/titles/title-ii/programs/acep/state-distribution
/pdl/programs/conservation/acep/subprograms
-- /pdl/titles/title-ii/programs/acep/subprograms

TITLE II RCPP
/pdl/programs/conservation/rcpp/state-distribution
-- /pdl/titles/title-ii/programs/rcpp/state-distribution
/pdl/programs/conservation/rcpp/subprograms
-- /pdl/titles/title-ii/programs/rcpp/subprograms

### CODE REVIEW

**Comment by ywkim312** [comment]
Title I
Subtitle A and others (ARC, PLC)
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-a/map
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-a/state-distribution
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-a/subprograms

Subtitle D
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-d/state-distribution
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-d/subprograms

Subtitle E
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-e/state-distribution
http://localhost:5000/pdl/titles/title-i/subtitles/subtitle-e/subprograms

Title II
EQIP
http://localhost:5000/pdl/titles/title-ii/programs/eqip/map
http://localhost:5000/pdl/titles/title-ii/programs/eqip/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/eqip/practice-categories

CSP
http://localhost:5000/pdl/titles/title-ii/programs/csp/map
http://localhost:5000/pdl/titles/title-ii/programs/csp/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/csp/practice-categories

CRP
http://localhost:5000/pdl/titles/title-ii/programs/crp/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/crp/subprograms

ACEP
http://localhost:5000/pdl/titles/title-ii/programs/acep/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/acep/subprograms

RCPP
http://localhost:5000/pdl/titles/title-ii/programs/rcpp/state-distribution
http://localhost:5000/pdl/titles/title-ii/programs/rcpp/subprograms

**Comment by ywkim312** [comment]
@sandeep-ps @pengyin-shan This one still have old commodities related json files. The recent data-import PR, the json file has been updated to use state abbreviation but I did not include those in this PR yet because it will break the frontend. Should I update the json files for commodities as well?

**Comment by pengyin-shan** [comment]
> @sandeep-ps @pengyin-shan This one still have old commodities related json files. The recent data-import PR, the json file has been updated to use state abbreviation but I did not include those in this PR yet because it will break the frontend. Should I update the json files for commodities as well?

Hi @ywkim312, thank you for updating this information. Is it possible to update all states in Title I and Title II to abbreviations in this PR? I'll then update the Title I and Title II pages to use both the new data and abbreviated state names, and make a front-end release for this.

After this release, you can merge the Abbreviation PR, and I can then update the rest of the pages to use abbreviations. Does this sounds good to you?

One more question and please pardon me for asking this...what is the difference between the `map` endpoint (ex: pdl/titles/title-ii/programs/csp/amp) and the `state-distribution` endpoint? (ex: /pdl/programs/conservation/csp/state-distribution). We used to have `state-distribution` for both map and table charts. Can you help me to recall why we want a new endpoint?

**Comment by ywkim312** [comment]
> > @sandeep-ps @pengyin-shan This one still have old commodities related json files. The recent data-import PR, the json file has been updated to use state abbreviation but I did not include those in this PR yet because it will break the frontend. Should I update the json files for commodities as well?
> 
> Hi @ywkim312, thank you for updating this information. Is it possible to update all states in Title I and Title II to abbreviations in this PR? I'll then update the Title I and Title II pages to use both the new data and abbreviated state names, and make a front-end release for this.
> 
> After this release, you can merge the Abbreviation PR, and I can then update the rest of the pages to use abbreviations. Does this sounds good to you?
> 
> One more question and please pardon me for asking this...what is the difference between the `map` endpoint (ex: pdl/titles/title-ii/programs/csp/amp) and the `state-distribution` endpoint? (ex: /pdl/programs/conservation/csp/state-distribution). We used to have `state-distribution` for both map and table charts. Can you help me to recall why we want a new endpoint?

In here, I believe that everything is state abbreviation except commodities. The reason why I didn't update the comodities is that, all others are having new endpoint so it will not break the current one, but commidities doesn't yet so it might break the things. Is it okay just overwrite the json files for comodities in this PR without createing new endpoint for those?

**Comment by ywkim312** [comment]
@pengyin-shan Oh, my bad, I think that commodities have new endpoints. I will update commodities json as the state abbreviation one as well. Sorry about that

**Comment by pengyin-shan** [comment]
> @pengyin-shan Oh, my bad, I think that commodities have new endpoints. I updated commodities json as the state abbreviation one as well. Sorry about that

cool, I also see the map endpoints are giving year-by-year data, which is good so let's leave them there. thank you!

**Review by pengyin-shan — APPROVED** [review]

**Comment by sandeep-ps** [comment]
Hi, Yongwook, I think we had discussed using "/summary" instead of "/subprograms" or "/practice-categories." It's also in the Google Doc linked to the GitHub issue. I think the idea was that the endpoint would provide a high-level summary of the program, sub-program, or practice category, whichever may precede. Please share your thoughts on this. Thanks.

After updating my local Postman collection, I have restarted testing the endpoints, and so far, it looks good. I will share further updates or questions soon. Thanks.

**Comment by sandeep-ps** [comment]
Other tests have succeeded. If it sounds good to you, we could have a follow-up task to mark the old endpoints deprecated in the YAML file.

**Comment by sandeep-ps** [comment]
Okay. The change that I brought up was about the URL and not the data, but it can be combined with data changes. I will approve this PR. Thanks.

**Review by sandeep-ps — APPROVED** [review]
Approving. Thanks.

**Pull request merged**
